services:
  - type: web
    name: egs-flask-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: MYSQL_HOST
        value: <your-mysql-host>
      - key: MYSQL_USER
        value: <your-mysql-user>
      - key: MYSQL_PASSWORD
        value: <your-mysql-password>
      - key: MYSQL_DB
        value: <your-mysql-db>
      - key: SECRET_KEY
        value: <your-secret-key>
